#!/usr/bin/env bash
#
# test-dev-firewall.sh — dev-firewall's stub matrix: a fresh arm in order, a
# convergent re-arm, every way an arm can fail without ever opening egress, the
# allowlist file, the toggle, the status report's annotation paths, the sudo
# re-exec, and the host guard.
#
# Run it from anywhere, on the host: bash .devcontainer/test/test-dev-firewall.sh
#
# `dev-firewall` is POSIX sh on purpose, and macOS /bin/sh is bash in POSIX
# mode — permissive enough to let a bashism through. Re-run the suite against
# the strictest interpreter the shebang can land on to catch that:
#
#   DEV_FIREWALL_SHELL=dash bash .devcontainer/test/test-dev-firewall.sh
#
# The scratch world, the reporting protocol, the safe bin, planting and the
# generic assertions come from test-helper.sh. Divergences the subject forces,
# all of them here:
#
#   - DEV_FIREWALL_ROOT prefixes every absolute runtime path, so the whole
#     script runs unprivileged inside a scratch world: /etc/resolv.conf, the
#     allowlist, the logs, the pid-files and /proc are all fixtures under $ROOT.
#   - `dig` is a stub, not the safe bin's copy: here it is the subject's DNS
#     probe — network — rather than one of its utilities. The case bin precedes
#     the safe bin on PATH, so the stub is what the subject resolves.
#   - The iptables stub keeps jump state in a file, so `-C` answers honestly
#     and idempotence is something the cases observe rather than assume; the
#     restore stubs record what they were fed on stdin, so rule *order* is
#     asserted against the real payload.

SUBJECT=dev-firewall
SUBJECT_PATH=.devcontainer/sbin/dev-firewall
SUBJECT_SHELL_VAR=DEV_FIREWALL_SHELL
# shellcheck source=.devcontainer/test/test-helper.sh
. "$(dirname "${BASH_SOURCE[0]}")/test-helper.sh"

# --- this suite's world extras ----------------------------------------------

ROOT="$TMP/root"
SENTINEL="$TMP/sentinel"
: >"$SENTINEL"

# The path the sudoers grant names and the rotator re-invokes: the image copy,
# never the planted one — a constant in the subject, so a constant here.
SELF=/usr/local/sbin/dev-firewall

# The three daemons' pids are fixed so the fixtures and the assertions can name
# them; the stubs plant $ROOT/proc/<pid> the way a live process would.
DNSMASQ_PID_VALUE=4242
ULOGD_PID_VALUE=4141
ROTATE_PID_VALUE=4343

# The allowlist as the image would carry it: comments, a blank line, a trailing
# comment on a domain line, and a host-level entry — everything the parser has
# to get right, and seven domains to count.
ALLOWLIST_FIXTURE='# fixture allowlist
anthropic.com
claude.ai
openai.com

github.com   # source hosting
npmjs.org
herdr.dev
playwright.download.prss.microsoft.com
'

# --- stubs ------------------------------------------------------------------

cat >"$STUBS/id" <<'STUB'
#!/bin/sh
printf '%s\n' "${ID_STUB_UID:-0}"
STUB

cat >"$STUBS/sudo" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'sudo %s\n' "$*" >>"$S/calls.log"
# -l is the grant probe, which is the only thing that can be "denied" here; the
# run itself is never actually re-executed, so a case can assert the escalation
# without the whole script running twice.
case " $* " in
*" -l "*) exit "${SUDO_STUB_LIST_RC:-0}" ;;
esac
exit 0
STUB

cat >"$STUBS/ip" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'ip %s\n' "$*" >>"$S/calls.log"
case "$*" in
*"route show default"*)
	echo 'default via 10.9.0.1 dev eth0'
	;;
*"route show proto kernel"*)
	echo '10.9.0.0/16 dev eth0 scope link src 10.9.0.7'
	;;
*)
	# A route the subject must never read: `ip route show` unfiltered would
	# hand back the default route too, and accepting its destination would
	# open everything.
	echo 'default via 10.9.0.1 dev eth0'
	echo '10.9.0.0/16 dev eth0 proto kernel scope link src 10.9.0.7'
	echo '192.168.0.0/16 via 10.9.0.9 dev eth0'
	;;
esac
STUB

# IPSET_STUB_FAIL is the subcommand to fail — `create`, `flush`, or `any` —
# because create and flush are separate fallible steps of an arm and the cases
# need to fail one without the other.
cat >"$STUBS/ipset" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'ipset %s\n' "$*" >>"$S/calls.log"
fail=${IPSET_STUB_FAIL:-}
if [ -n "$fail" ] && { [ "$fail" = any ] || [ "$fail" = "${1:-}" ]; }; then
	echo 'ipset stub: Kernel error received: Operation not permitted' >&2
	exit 1
fi
exit 0
STUB

# One binary for both families: which one ran is already in the call log, and
# the jump state is per-family so `-C` can answer honestly.
cat >"$STUBS/iptables" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
me=${0##*/}
printf '%s %s\n' "$me" "$*" >>"$S/calls.log"
jumps="$S/jumps-$me"
count=$(cat "$jumps" 2>/dev/null || echo 0)
case "$*" in
"-C OUTPUT -j "*)
	[ "$count" -gt 0 ] || exit 1
	;;
"-I OUTPUT 1 -j "*)
	echo $((count + 1)) >"$jumps"
	;;
"-D OUTPUT -j "*)
	echo $((count - 1)) >"$jumps"
	;;
*)
	echo "iptables stub: unsupported: $*" >&2
	exit 2
	;;
esac
exit 0
STUB

# Logged *after* stdin is drained: the ruleset is generated by the other half of
# a pipeline, so logging first would race the `ip` calls that build it and make
# the call order nondeterministic.
#
# An arm feeds each family twice — the minimal deny floor, then the full
# ruleset — so every payload is kept under its own ordinal alongside the
# latest-wins file the ruleset_* helpers read. The failure knobs are selective
# on both counts, because "the full v6 restore is the one that fails" is a
# distinct fresh-container state from "nothing restores at all":
#
#   RESTORE_STUB_FAIL             every restore, either family, either payload
#   RESTORE_STUB_FAIL_FULL=<name> the full ruleset only, for that binary or `all`
#   RESTORE_STUB_FAIL_MIN=<name>  the minimal deny only, same
#
# Which payload is which is read off the marker comment the subject emits;
# iptables-restore ignores `#` lines, so the marker costs the real fence nothing.
cat >"$STUBS/iptables-restore" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
me=${0##*/}
payload=$(cat)
printf '%s %s\n' "$me" "$*" >>"$S/calls.log"
n=$(cat "$S/restores-$me" 2>/dev/null || echo 0)
n=$((n + 1))
printf '%s\n' "$n" >"$S/restores-$me"
printf '%s\n' "$payload" >"$S/ruleset-$me.$n.txt"
printf '%s\n' "$payload" >"$S/ruleset-$me.txt"
kind=other
case "$payload" in
'# dev-firewall minimal deny'*) kind=min ;;
'# dev-firewall full ruleset'*) kind=full ;;
esac
fail=${RESTORE_STUB_FAIL:-}
case "$kind:${RESTORE_STUB_FAIL_FULL:-}" in
full:all | "full:$me") fail=1 ;;
esac
case "$kind:${RESTORE_STUB_FAIL_MIN:-}" in
min:all | "min:$me") fail=1 ;;
esac
[ -n "$fail" ] && {
	echo "$me stub: line 4 failed" >&2
	exit 1
}
exit 0
STUB

cat >"$STUBS/dnsmasq" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'dnsmasq %s\n' "$*" >>"$S/calls.log"
conf=''
prev=''
for arg in "$@"; do
	[ "$prev" = -C ] && conf=$arg
	prev=$arg
done
case " $* " in
*" --test "*)
	[ -n "${DNSMASQ_STUB_TEST_FAIL:-}" ] && {
		echo 'dnsmasq stub: bad option at line 9 of the config file' >&2
		exit 1
	}
	echo 'dnsmasq stub: syntax check OK.'
	exit 0
	;;
esac
[ -n "${DNSMASQ_STUB_START_FAIL:-}" ] && {
	echo 'dnsmasq stub: failed to create listening socket for 127.0.0.1: Address already in use' >&2
	exit 1
}
# The real daemon writes the pid-file named in its own config, so the stub
# reads it from there too rather than being told twice.
pidfile=$(sed -n 's/^pid-file=//p' "$conf" 2>/dev/null)
[ -n "$pidfile" ] || exit 1
printf '%s\n' "${DNSMASQ_STUB_PID:?}" >"$pidfile"
mkdir -p "${DEV_FIREWALL_ROOT:?}/proc/${DNSMASQ_STUB_PID}"
exit 0
STUB

cat >"$STUBS/ulogd" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'ulogd %s\n' "$*" >>"$S/calls.log"
[ -n "${ULOGD_STUB_FAIL:-}" ] && {
	echo 'ulogd stub: can not open file: No such file or directory' >&2
	exit 1
}
pidfile=''
prev=''
for arg in "$@"; do
	[ "$prev" = -p ] && pidfile=$arg
	prev=$arg
done
[ -n "$pidfile" ] || exit 1
printf '%s\n' "${ULOGD_STUB_PID:?}" >"$pidfile"
mkdir -p "${DEV_FIREWALL_ROOT:?}/proc/${ULOGD_STUB_PID}"
exit 0
STUB

# Both halves of the tool the subject uses: --stop reaps the pid-file and the
# planted /proc entry, --start plants them, the way a real backgrounded daemon
# would. SSD_STUB_FAIL fails either, because "the rotator will not start" and
# "the running one will not die" are both arm failures the cases exercise.
cat >"$STUBS/start-stop-daemon" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'start-stop-daemon %s\n' "$*" >>"$S/calls.log"
[ -n "${SSD_STUB_FAIL:-}" ] && {
	echo 'start-stop-daemon stub: refused' >&2
	exit 2
}
pidfile=''
prev=''
for arg in "$@"; do
	[ "$prev" = --pidfile ] && pidfile=$arg
	prev=$arg
done
[ -n "$pidfile" ] || exit 1
case " $* " in
*" --start "*)
	printf '%s\n' "${SSD_STUB_PID:?}" >"$pidfile"
	mkdir -p "${DEV_FIREWALL_ROOT:?}/proc/${SSD_STUB_PID}"
	;;
*)
	if [ -f "$pidfile" ]; then
		pid=$(cat "$pidfile")
		rm -rf "${DEV_FIREWALL_ROOT:?}/proc/$pid"
		rm -f "$pidfile"
	fi
	;;
esac
exit 0
STUB

# Granted only where the single-pass claim is under test: it records what awk was
# asked to read and then runs the real one, so "the DNS log is read exactly once"
# is an assertion rather than an argument.
cat >"$STUBS/awk" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'awk %s\n' "$*" >>"$S/calls.log"
exec "${REAL_AWK:?}" "$@"
STUB

cat >"$STUBS/getent" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'getent %s\n' "$*" >>"$S/calls.log"
# A tiny reverse-lookup table: only the address the dnsmasq query log does not
# know about is in here, so the two annotation paths stay distinguishable.
case "${2:-}" in
203.0.113.9) echo '203.0.113.9     reverse.example.net' ;;
*) exit 2 ;;
esac
STUB

# The probe. DIG_STUB_ANSWER is what it prints; the subject compares that against
# the literal 127.0.0.1, so "dnsmasq answers something else" and "dnsmasq answers
# nothing" are both one knob away.
cat >"$STUBS/dig" <<'STUB'
#!/bin/sh
set -u
S=${STUB_STATE:?}
printf 'dig %s\n' "$*" >>"$S/calls.log"
printf '%s\n' "${DIG_STUB_ANSWER-127.0.0.1}"
exit 0
STUB

chmod +x "$STUBS"/*
# iptables-restore is the subject of both restore stubs, and iptables of both
# families: one file each, linked under every name the script calls.
for name in ip6tables; do ln -sf "$STUBS/iptables" "$STUBS/$name"; done
for name in ip6tables-restore; do ln -sf "$STUBS/iptables-restore" "$STUBS/$name"; done

# --- the case harness -------------------------------------------------------

RESOLV_FIXTURE='# Generated by Docker Engine.
nameserver 127.0.0.11
search internal.example
options ndots:0'

ALL_STUBS='id sudo ip ipset iptables ip6tables iptables-restore
ip6tables-restore dnsmasq ulogd start-stop-daemon getent dig'

CONF="$ROOT/etc/dev-firewall"
RUN="$ROOT/run/dev-firewall"
LOG_DIR="$ROOT/var/log"
ALLOWLIST="$CONF/allowlist"

reset_world() {
	rm -rf "$STATE" "$ROOT"
	mkdir -p "$STATE" "$ROOT/etc" "$ROOT/var/log" "$ROOT/run" "$ROOT/proc" "$CONF"
	# Discovered, not pinned: the subject globs the multiarch plugin directory,
	# so the fixture has to look multiarch too.
	mkdir -p "$ROOT/usr/lib/aarch64-linux-gnu/ulogd"
	printf '%s\n' "$RESOLV_FIXTURE" >"$ROOT/etc/resolv.conf"
	# The image's copy of the tracked allowlist.
	printf '%s' "$ALLOWLIST_FIXTURE" >"$ALLOWLIST"
	# shellcheck disable=SC2086
	grant $ALL_STUBS
	SENTINEL="$TMP/sentinel"
	unset ID_STUB_UID SUDO_STUB_LIST_RC IPSET_STUB_FAIL RESTORE_STUB_FAIL \
		RESTORE_STUB_FAIL_FULL RESTORE_STUB_FAIL_MIN \
		DNSMASQ_STUB_TEST_FAIL DNSMASQ_STUB_START_FAIL ULOGD_STUB_FAIL \
		SSD_STUB_FAIL DIG_STUB_ANSWER DEV_FIREWALL_LOG_MAX
	OUT=''
	ERR=''
	RC=0
}

# runp <args…> — the planted script with a hermetic PATH and a scratch
# filesystem root.
runp() {
	capture --cd "$REPO" env -i \
		PATH="$CASEBIN:$SAFEBIN" \
		HOME="$TMP" \
		STUB_STATE="$STATE" \
		DEV_FIREWALL_SENTINEL="$SENTINEL" \
		DEV_FIREWALL_ROOT="$ROOT" \
		DNSMASQ_STUB_PID="$DNSMASQ_PID_VALUE" \
		ULOGD_STUB_PID="$ULOGD_PID_VALUE" \
		SSD_STUB_PID="$ROTATE_PID_VALUE" \
		REAL_AWK="$SAFEBIN/awk" \
		${DEV_FIREWALL_LOG_MAX+DEV_FIREWALL_LOG_MAX="$DEV_FIREWALL_LOG_MAX"} \
		${ID_STUB_UID+ID_STUB_UID="$ID_STUB_UID"} \
		${SUDO_STUB_LIST_RC+SUDO_STUB_LIST_RC="$SUDO_STUB_LIST_RC"} \
		${IPSET_STUB_FAIL+IPSET_STUB_FAIL="$IPSET_STUB_FAIL"} \
		${RESTORE_STUB_FAIL+RESTORE_STUB_FAIL="$RESTORE_STUB_FAIL"} \
		${RESTORE_STUB_FAIL_FULL+RESTORE_STUB_FAIL_FULL="$RESTORE_STUB_FAIL_FULL"} \
		${RESTORE_STUB_FAIL_MIN+RESTORE_STUB_FAIL_MIN="$RESTORE_STUB_FAIL_MIN"} \
		${DNSMASQ_STUB_TEST_FAIL+DNSMASQ_STUB_TEST_FAIL="$DNSMASQ_STUB_TEST_FAIL"} \
		${DNSMASQ_STUB_START_FAIL+DNSMASQ_STUB_START_FAIL="$DNSMASQ_STUB_START_FAIL"} \
		${ULOGD_STUB_FAIL+ULOGD_STUB_FAIL="$ULOGD_STUB_FAIL"} \
		${SSD_STUB_FAIL+SSD_STUB_FAIL="$SSD_STUB_FAIL"} \
		${DIG_STUB_ANSWER+DIG_STUB_ANSWER="$DIG_STUB_ANSWER"} \
		"$REPO/$SUBJECT_PATH" "$@"
}

ruleset() { cat "$STATE/ruleset-${1:-iptables-restore}.txt" 2>/dev/null; }

# The deny floor is always the first payload a family is fed, so the minimal
# ruleset stays inspectable even in the cases where a later full restore
# overwrote the latest-wins file with what it *attempted*.
min_ruleset() { cat "$STATE/ruleset-${1:-iptables-restore}.1.txt" 2>/dev/null; }

restores() { cat "$STATE/restores-${1:-iptables-restore}" 2>/dev/null || echo 0; }

ruleset_has() {
	ruleset "${2:-iptables-restore}" | grep -qF -- "$1" ||
		die "the ${2:-iptables-restore} payload lacks: $1
$(ruleset "${2:-iptables-restore}")"
	ok "ruleset: $1"
}

ruleset_hasnt() {
	ruleset "${2:-iptables-restore}" | grep -qF -- "$1" &&
		die "the ${2:-iptables-restore} payload should not contain: $1
$(ruleset "${2:-iptables-restore}")"
	ok "ruleset lacks: $1"
}

min_ruleset_has() {
	min_ruleset "${2:-iptables-restore}" | grep -qF -- "$1" ||
		die "the ${2:-iptables-restore} deny floor lacks: $1
$(min_ruleset "${2:-iptables-restore}")"
	ok "deny floor (${2:-iptables-restore}): $1"
}

min_ruleset_hasnt() {
	min_ruleset "${2:-iptables-restore}" | grep -qF -- "$1" &&
		die "the ${2:-iptables-restore} deny floor should not contain: $1
$(min_ruleset "${2:-iptables-restore}")"
	ok "deny floor (${2:-iptables-restore}) lacks: $1"
}

# The floor's resolver gate is worthless below the floor's loopback accept, so its
# position is asserted there too, not only in the full ruleset.
min_ruleset_before() {
	local a b
	a=$(min_ruleset | grep -nF -- "$1" | head -1 | cut -d: -f1)
	b=$(min_ruleset | grep -nF -- "$2" | head -1 | cut -d: -f1)
	[ -n "$a" ] || die "not in the deny floor: $1"
	[ -n "$b" ] || die "not in the deny floor: $2"
	[ "$a" -lt "$b" ] || die "'$1' (line $a) is not above '$2' (line $b)"
	ok "deny floor: '$1' comes before '$2'"
}

restores_are() {
	[ "$(restores "${2:-iptables-restore}")" = "$1" ] ||
		die "${2:-iptables-restore} was fed $(restores "${2:-iptables-restore}") payload(s), expected $1"
	ok "${2:-iptables-restore} was fed $1 payload(s)"
}

# ruleset_before <earlier> <later> — rule order is the whole security argument
# here, so it is asserted rather than eyeballed.
ruleset_before() {
	local a b
	a=$(ruleset | grep -nF -- "$1" | head -1 | cut -d: -f1)
	b=$(ruleset | grep -nF -- "$2" | head -1 | cut -d: -f1)
	[ -n "$a" ] || die "not in the ruleset: $1"
	[ -n "$b" ] || die "not in the ruleset: $2"
	[ "$a" -lt "$b" ] || die "'$1' (line $a) is not above '$2' (line $b)"
	ok "ruleset: '$1' comes before '$2'"
}

resolv_is_fixture() {
	[ "$(cat "$ROOT/etc/resolv.conf")" = "$RESOLV_FIXTURE" ] ||
		die "resolv.conf was rewritten:
$(cat "$ROOT/etc/resolv.conf")"
	ok 'resolv.conf is untouched'
}

jumps() { cat "$STATE/jumps-${1:-iptables}" 2>/dev/null || echo 0; }

jumps_are() {
	[ "$(jumps "${2:-iptables}")" = "$1" ] ||
		die "${2:-iptables} OUTPUT holds $(jumps "${2:-iptables}") jump(s), expected $1"
	ok "${2:-iptables} OUTPUT holds $1 jump(s)"
}

# The rotator the arm leaves behind: a `dev-firewall rotate` a minute, run by the
# same start-stop-daemon the script stops its daemons with. Named once here,
# because the exact command line is what the call-log assertions pin — including
# that the loop re-invokes the *image* copy, not whatever file happened to run.
ROTATOR_START="start-stop-daemon --start --quiet --background --make-pidfile --pidfile $RUN/rotate.pid --startas /bin/sh -- -c while :; do \"$SELF\" rotate || exit 1; sleep 60; done"
ROTATOR_STOP="start-stop-daemon --stop --quiet --oknodo --retry TERM/5/KILL/5 --pidfile $RUN/rotate.pid --remove-pidfile"

# The probe, pinned once: a single named server, the answer alone, and both
# timing bounds — so a resolver that is up but silent cannot hang an arm.
DIG_PROBE='dig @127.0.0.1 +short +time=2 +tries=1 dev-firewall.probe'

# file_size_is <bytes> <path> — retention is about sizes, so they are asserted
# rather than inferred from a grep. The arithmetic strips wc's padding.
file_size_is() {
	local n
	[ -f "$2" ] || die "no such file: $2"
	n=$(($(wc -c <"$2")))
	[ "$n" = "$1" ] || die "$2 holds $n byte(s), expected $1"
	ok "$(basename "$2"): $1 byte(s)"
}

# ============================================================================
# Arming
# ============================================================================

case_start 'a fresh arm establishes the deny posture before the convenience layer'
reset_world
runp on
rc_is 0
out_has 'enforcement: armed (7 domains allowlisted)'
# The order *is* the fail-closed guarantee: the minimal deny and its jump land
# per family before anything fallible runs at all, the full ruleset replaces the
# floor in place, the daemons come after the rules, and resolv.conf is flipped
# only once the resolver has answered.
log_is \
	'iptables-restore --noflush' \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'iptables -I OUTPUT 1 -j DEV_FIREWALL' \
	'ip6tables-restore --noflush' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -I OUTPUT 1 -j DEV_FIREWALL' \
	"dnsmasq --test -C $CONF/dnsmasq.conf" \
	'ipset create dev-allowed hash:ip -exist' \
	'ipset flush dev-allowed' \
	'ip -4 route show default' \
	'ip -4 route show proto kernel' \
	'iptables-restore --noflush' \
	'ip6tables-restore --noflush' \
	"ulogd -d -c $CONF/ulogd.conf -p $RUN/ulogd.pid" \
	"dnsmasq -C $CONF/dnsmasq.conf" \
	"$ROTATOR_START" \
	"$DIG_PROBE"
jumps_are 1
jumps_are 1 ip6tables

case_start 'the deny floor lands before anything that can fail'
# On a *fresh* container the first external call an arm makes is the one that
# closes egress, so every failure after it is wedged rather than open.
called_before 'iptables-restore --noflush' "dnsmasq --test -C $CONF/dnsmasq.conf"
called_before 'iptables -I OUTPUT 1 -j DEV_FIREWALL' 'ipset create dev-allowed hash:ip -exist'
called_before 'ip6tables -I OUTPUT 1 -j DEV_FIREWALL' 'ipset create dev-allowed hash:ip -exist'
restores_are 2
restores_are 2 ip6tables-restore
ok 'each family is fed the floor first and the full ruleset second'
# Composition: a REJECT catch-all per family, over the same lo and conntrack
# accepts the full rulesets open with — so the floor is never looser than the
# posture it stands in for, and a re-arm's replace window never RSTs a live
# connection.
min_ruleset_has '-A DEV_FIREWALL -o lo -j ACCEPT'
min_ruleset_has '-A DEV_FIREWALL -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT'
min_ruleset_has '-A DEV_FIREWALL -j REJECT --reject-with icmp-port-unreachable'
min_ruleset_has '-A DEV_FIREWALL -o lo -j ACCEPT' ip6tables-restore
min_ruleset_has '-A DEV_FIREWALL -j REJECT --reject-with icmp6-port-unreachable' ip6tables-restore
# Nothing in the floor may depend on the convenience layer: the ipset does not
# exist yet and the logger is not running.
min_ruleset_hasnt '--match-set'
min_ruleset_hasnt 'NFLOG'
min_ruleset_hasnt '--match-set' ip6tables-restore
min_ruleset_hasnt 'NFLOG' ip6tables-restore
ok 'the floor depends on neither the ipset nor the logger'
# The resolver gate is in the floor too, hardcoded: a failed arm would otherwise
# leave Docker's embedded resolver reachable by every identity indefinitely, on a
# container agents are already attached to. Nothing fallible feeds it — the
# address is a literal, not a lookup.
min_ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -m owner --uid-owner 0 -j ACCEPT'
min_ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -j REJECT --reject-with icmp-port-unreachable'
min_ruleset_before '-d 127.0.0.11 -j REJECT' '-A DEV_FIREWALL -o lo -j ACCEPT'
min_ruleset_before '--uid-owner 0 -j ACCEPT' '-d 127.0.0.11 -j REJECT'
# An IPv4 literal in a v6 ruleset is a payload the kernel rejects, and the v6 set
# is a blanket deny anyway.
min_ruleset_hasnt '127.0.0.11' ip6tables-restore
min_ruleset_hasnt '--uid-owner' ip6tables-restore

case_start 'the v4 ruleset is ordered so nothing widens the fence'
ruleset_has '*filter'
ruleset_has '-F DEV_FIREWALL'
ok 'the chain is declared and flushed inside the payload — one kernel transaction'
ruleset_has '-A DEV_FIREWALL -o lo -j ACCEPT'
ruleset_has '-A DEV_FIREWALL -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT'
# The gateway is the host on a Linux box, so it is rejected *before* the
# connected-subnet accept that would otherwise cover it.
ruleset_has '-A DEV_FIREWALL -d 10.9.0.1 -j REJECT'
ruleset_before '-d 10.9.0.1 -j REJECT' '-d 10.9.0.0/16 -j ACCEPT'
ruleset_has '-A DEV_FIREWALL -d 10.9.0.0/16 -j ACCEPT'
# Only `proto kernel` routes: the stub also offers a default route and a
# learned 192.168/16, and admitting either would open the operator's LAN.
ruleset_hasnt '192.168.0.0/16'
ruleset_hasnt '-d default'
ok 'only directly connected subnets are accepted'
# No port match anywhere: git talks SSH to github.com.
ruleset_has '-A DEV_FIREWALL -m set --match-set dev-allowed dst -j ACCEPT'
ruleset_hasnt '--dport'
ok 'the allowlist accepts every port, not just 443'
ruleset_before '--match-set dev-allowed dst -j ACCEPT' '-A DEV_FIREWALL -j NFLOG'
ruleset_before '-A DEV_FIREWALL -j NFLOG' '-A DEV_FIREWALL -j REJECT'
ok 'the catch-all logs before it rejects'
ruleset_has '-j REJECT --reject-with icmp-port-unreachable'
ruleset_hasnt '-j DROP'
ok 'the verdict is REJECT, so a denial fails in milliseconds instead of hanging'
ruleset_has '--nflog-group 1'
ruleset_has '--nflog-prefix "dev-firewall"'

case_start 'the local dnsmasq is the only resolver an unprivileged process reaches'
# Docker's embedded resolver is on loopback, so the blanket `-o lo -j ACCEPT`
# left it reachable by any identity: /etc/resolv.conf only redirects processes
# that consult it, and naming 127.0.0.11 directly resolved non-allowlisted names
# while status said `armed`. dnsmasq runs as root, so the gate is written as
# "accept uid 0, reject the rest" — never as "reject uid 1000", which the
# devcontainer CLI is free to remap.
ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -m owner --uid-owner 0 -j ACCEPT'
ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -j NFLOG --nflog-group 1 --nflog-prefix "dev-firewall"'
ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -j REJECT --reject-with icmp-port-unreachable'
# Position is the whole security argument: below the loopback accept the gate
# would never be consulted, and below its own REJECT the resolver could not
# forward.
ruleset_before '-d 127.0.0.11 -m owner --uid-owner 0 -j ACCEPT' '-d 127.0.0.11 -j REJECT'
ruleset_before '-d 127.0.0.11 -j REJECT' '-A DEV_FIREWALL -o lo -j ACCEPT'
ok 'the gate sits above the loopback accept it exists to narrow'
ruleset_before '-d 127.0.0.11 -j NFLOG' '-d 127.0.0.11 -j REJECT'
ok 'a process reaching for the embedded resolver is logged like any other denial'
# 127.0.0.1 is dnsmasq's own listener, and gating it would reject every name
# lookup in the container.
ruleset_hasnt '-d 127.0.0.1 -j REJECT'
ruleset_hasnt '-d 127.0.0.0/8'

case_start 'the v6 ruleset is a blanket deny with no allowlist'
ruleset_has '-A DEV_FIREWALL -o lo -j ACCEPT' ip6tables-restore
ruleset_has '-A DEV_FIREWALL -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT' ip6tables-restore
ruleset_has '-j REJECT --reject-with icmp6-port-unreachable' ip6tables-restore
ruleset_hasnt '--match-set' ip6tables-restore
ok 'no v6 allowlist: the compose network has no IPv6 to allow'

case_start 'the generated dnsmasq config is the allowlist file, and forwards to Docker'
file_has "$CONF/dnsmasq.conf" 'no-resolv'
# The upstream is Docker's embedded DNS, which is what resolves the other
# compose services — fencing a project's database would be the first thing
# anyone noticed.
file_has "$CONF/dnsmasq.conf" 'server=127.0.0.11'
file_has "$CONF/dnsmasq.conf" 'listen-address=127.0.0.1'
file_has "$CONF/dnsmasq.conf" 'log-queries'
file_has "$CONF/dnsmasq.conf" "log-facility=$ROOT/var/log/dev-firewall-dns.log"
file_has "$CONF/dnsmasq.conf" 'address=/dev-firewall.probe/127.0.0.1'
file_counts 7 "$CONF/dnsmasq.conf" '^ipset=/'
file_has "$CONF/dnsmasq.conf" 'ipset=/github.com/dev-allowed'
file_has "$CONF/dnsmasq.conf" 'ipset=/npmjs.org/dev-allowed'
file_has "$CONF/dnsmasq.conf" 'ipset=/anthropic.com/dev-allowed'
file_has "$CONF/dnsmasq.conf" 'ipset=/herdr.dev/dev-allowed'
# A host-level entry, not a suffix — proof the generator does not assume
# two-label domains anywhere.
file_has "$CONF/dnsmasq.conf" 'ipset=/playwright.download.prss.microsoft.com/dev-allowed'
# The parser: the comment lines, the blank line and the trailing comment on
# the github line all vanish, and the domain beside that comment survives.
file_hasnt "$CONF/dnsmasq.conf" 'fixture allowlist'
file_hasnt "$CONF/dnsmasq.conf" 'source hosting'
file_counts 0 "$CONF/dnsmasq.conf" '^ipset=//'
file_counts 0 "$CONF/dnsmasq.conf" '^ipset=/[^/]* '
ok 'comments and blank lines in the allowlist produce no ipset lines'
file_has "$CONF/dnsmasq.conf" "from $ALLOWLIST"
ok 'the generated config names the file it was generated from'
file_has "$CONF/upstream" '127.0.0.11'
ok 'the displaced nameserver is recorded before resolv.conf is overwritten'

case_start 'the generated ulogd config stacks NFLOG group 1 onto the denial log'
file_has "$CONF/ulogd.conf" 'stack=denials:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTPKT,emu1:LOGEMU'
file_has "$CONF/ulogd.conf" 'group=1'
file_has "$CONF/ulogd.conf" "file=\"$ROOT/var/log/dev-firewall.log\""
file_has "$CONF/ulogd.conf" 'sync=1'
file_has "$CONF/ulogd.conf" "$ROOT/usr/lib/aarch64-linux-gnu/ulogd/ulogd_inppkt_NFLOG.so"
ok 'the multiarch plugin path is discovered, not pinned'

case_start 'resolv.conf points at dnsmasq alone, keeping search and options'
file_has "$ROOT/etc/resolv.conf" 'nameserver 127.0.0.1'
file_counts 1 "$ROOT/etc/resolv.conf" '^nameserver'
ok 'exactly one nameserver: a fallback would silently bypass the ipset feeding'
file_hasnt "$ROOT/etc/resolv.conf" 'nameserver 127.0.0.11'
file_has "$ROOT/etc/resolv.conf" 'search internal.example'
file_has "$ROOT/etc/resolv.conf" 'options ndots:0'

case_start 'the allowlist file is read, never written'
file_is "$ALLOWLIST_FIXTURE" "$ALLOWLIST"
ok 'the arm left the file byte-identical — the flow is repo to image to container, one way'

case_start 'a second arm converges instead of stacking'
: >"$STATE/calls.log"
runp on
rc_is 0
jumps_are 1
ok 'the OUTPUT jump is not inserted twice'
called 'iptables -C OUTPUT -j DEV_FIREWALL'
not_called 'iptables -I OUTPUT 1 -j DEV_FIREWALL'
# The set is flushed on every arm so an allowlist *removal* takes effect; live
# connections survive it through the conntrack rule.
called 'ipset flush dev-allowed'
# Both daemons are already up, so this time they are stopped by pid-file first.
called "start-stop-daemon --stop --quiet --oknodo --retry TERM/5/KILL/5 --pidfile $RUN/ulogd.pid --remove-pidfile"
called "start-stop-daemon --stop --quiet --oknodo --retry TERM/5/KILL/5 --pidfile $RUN/dnsmasq.pid --remove-pidfile"
called "dnsmasq -C $CONF/dnsmasq.conf"
# The rotator is a supervised daemon like the other two: stopped by pid-file and
# started again, so a re-arm never leaves two timers rotating the same logs.
called "$ROTATOR_STOP"
called "$ROTATOR_START"
called_before "$ROTATOR_STOP" "$ROTATOR_START"
file_has "$ROOT/etc/resolv.conf" 'nameserver 127.0.0.1'
file_counts 1 "$ROOT/etc/resolv.conf" '^nameserver'
ok 'a re-arm does not stack nameserver lines either'
file_has "$CONF/upstream" '127.0.0.11'
ok 'the upstream survives a re-arm, though resolv.conf no longer names it'

case_start 'a re-arm picks up an allowlist pushed in since the last one'
# `devc firewall allow` rewrites the file and re-arms; the generated config has
# to follow the file, not a cached reading of it.
printf '%s\n' 'example.net' >>"$ALLOWLIST"
runp on
rc_is 0
out_has 'enforcement: armed (8 domains allowlisted)'
file_has "$CONF/dnsmasq.conf" 'ipset=/example.net/dev-allowed'
file_counts 8 "$CONF/dnsmasq.conf" '^ipset=/'

case_start 'a non-loopback upstream is not a bypass, so the full ruleset gates nothing'
reset_world
# A host whose Docker hands out a routable nameserver instead of the embedded one:
# that address is already subject to the ordinary ruleset, and a gate on it would
# be a rule about the wrong thing.
printf '%s\n' '# Generated by Docker Engine.' 'nameserver 10.9.0.53' >"$ROOT/etc/resolv.conf"
runp on
rc_is 0
file_has "$CONF/upstream" '10.9.0.53'
ruleset_hasnt '--uid-owner'
ruleset_hasnt '-d 10.9.0.53'
# The floor's gate is a literal, not a derivation, so it stands either way.
min_ruleset_has '-A DEV_FIREWALL -d 127.0.0.11 -m owner --uid-owner 0 -j ACCEPT'
ok 'the gate follows the recorded upstream, and the floor guards the embedded resolver regardless'

# ============================================================================
# Every way an arm can fail leaves egress closed
# ============================================================================

case_start 'a missing allowlist stops the arm with the deny floor already down'
reset_world
rm -f "$ALLOWLIST"
runp on
rc_nonzero
err_has "no allowlist at $ALLOWLIST"
err_has 'devc rebuild'
# The file is read after the floor, like everything fallible: a broken image
# leaves the container closed, never open.
log_is \
	'iptables-restore --noflush' \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'iptables -I OUTPUT 1 -j DEV_FIREWALL' \
	'ip6tables-restore --noflush' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -I OUTPUT 1 -j DEV_FIREWALL'
jumps_are 1
jumps_are 1 ip6tables
min_ruleset_has '-j REJECT --reject-with icmp-port-unreachable'
no_file "$CONF/dnsmasq.conf"
resolv_is_fixture
ok 'closed and wedged, with nothing generated from a file that is not there'

case_start 'an allowlist with nothing in it is refused the same way'
reset_world
printf '%s\n' '# nothing here' '' '   # or here' >"$ALLOWLIST"
runp on
rc_nonzero
err_has "the allowlist at $ALLOWLIST is empty"
jumps_are 1
jumps_are 1 ip6tables
no_file "$CONF/dnsmasq.conf"
resolv_is_fixture
ok 'a file of comments is empty, and empty is a misconfiguration rather than a posture'

case_start 'a config dnsmasq rejects stops the arm with the deny floor already down'
reset_world
DNSMASQ_STUB_TEST_FAIL=1 runp on
rc_nonzero
err_has 'dnsmasq rejected the generated config'
# The floor moves first, deliberately: the config check is the earliest fallible
# step after the allowlist read, and on a fresh container it would otherwise
# exit with the chain still empty.
log_is \
	'iptables-restore --noflush' \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'iptables -I OUTPUT 1 -j DEV_FIREWALL' \
	'ip6tables-restore --noflush' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -I OUTPUT 1 -j DEV_FIREWALL' \
	"dnsmasq --test -C $CONF/dnsmasq.conf"
ok 'no daemon was started and no convenience rule was built'
jumps_are 1
jumps_are 1 ip6tables
min_ruleset_has '-j REJECT --reject-with icmp-port-unreachable'
min_ruleset_has '-j REJECT --reject-with icmp6-port-unreachable' ip6tables-restore
ok 'the chain the jumps point at rejects — closed, not empty'
resolv_is_fixture

case_start 'a failed arm from a fresh state still closes egress'
reset_world
DNSMASQ_STUB_START_FAIL=1 runp on
rc_nonzero
err_has 'dnsmasq failed to start'
# The point of the ordering: the deny rules and the jump are already in place
# when the convenience layer fails, so the container is stricter than intended
# rather than open.
jumps_are 1
jumps_are 1 ip6tables
called 'iptables -I OUTPUT 1 -j DEV_FIREWALL'
resolv_is_fixture
ok 'egress is closed and name resolution is left alone — the wedged-fence state'

case_start 'a failed logger fails the arm the same way'
reset_world
ULOGD_STUB_FAIL=1 runp on
rc_nonzero
err_has 'ulogd failed to start'
err_has 'denials would go unlogged'
jumps_are 1
not_called 'dnsmasq -C'
resolv_is_fixture

case_start 'a resolver that never answers leaves resolv.conf alone'
reset_world
DIG_STUB_ANSWER='' runp on
rc_nonzero
err_has 'dnsmasq is not answering on 127.0.0.1'
err_has 'leaving /etc/resolv.conf alone'
jumps_are 1
resolv_is_fixture
called_times 5 "$DIG_PROBE"
ok 'the probe is what gates the resolver flip, not the fact that dnsmasq started'

case_start 'a resolver that answers the wrong thing is not trusted either'
reset_world
# Some other resolver on 127.0.0.1 answering the probe name from a wildcard:
# whatever it is, it is not the dnsmasq feeding the ipset.
DIG_STUB_ANSWER='10.0.0.1' runp on
rc_nonzero
err_has 'dnsmasq is not answering on 127.0.0.1'
resolv_is_fixture

case_start 'an ipset the kernel refuses names the missing capability'
reset_world
IPSET_STUB_FAIL=create runp on
rc_nonzero
err_has 'cap_add: NET_ADMIN'
# One payload per family — the floor — and none of the full ruleset that would
# have needed the set that does not exist.
restores_are 1
restores_are 1 ip6tables-restore
jumps_are 1
jumps_are 1 ip6tables
min_ruleset_has '-j REJECT --reject-with icmp-port-unreachable'
min_ruleset_hasnt '--match-set'
resolv_is_fixture

case_start 'an ipset flush the kernel refuses closes egress the same way'
reset_world
IPSET_STUB_FAIL=flush runp on
rc_nonzero
err_has 'cannot flush the dev-allowed ipset'
called 'ipset create dev-allowed hash:ip -exist'
restores_are 1
restores_are 1 ip6tables-restore
jumps_are 1
jumps_are 1 ip6tables
resolv_is_fixture
ok 'create and flush are separate fallible steps, and both fail closed'

case_start 'a rejected v4 ruleset leaves the deny floor enforcing'
reset_world
RESTORE_STUB_FAIL_FULL=iptables-restore runp on
rc_nonzero
err_has 'iptables rejected the DEV_FIREWALL ruleset'
# The kernel kept the floor the failed restore never replaced; the stub world
# can only show the jumps and the floor payload that went in before it.
jumps_are 1
jumps_are 1 ip6tables
min_ruleset_has '-A DEV_FIREWALL -j REJECT --reject-with icmp-port-unreachable'
not_called 'ulogd'
resolv_is_fixture

case_start 'a rejected v6 ruleset fails the arm with both families still closed'
reset_world
RESTORE_STUB_FAIL_FULL=ip6tables-restore runp on
rc_nonzero
err_has 'ip6tables rejected the DEV_FIREWALL ruleset'
# The v4 full ruleset already landed; v6 is back to its floor, which is a
# blanket deny anyway.
ruleset_has '-A DEV_FIREWALL -m set --match-set dev-allowed dst -j ACCEPT'
jumps_are 1
jumps_are 1 ip6tables
min_ruleset_has '-A DEV_FIREWALL -j REJECT --reject-with icmp6-port-unreachable' ip6tables-restore
not_called 'ulogd'
resolv_is_fixture

case_start 'a floor the kernel rejects is reported honestly rather than claimed closed'
reset_world
# The one fresh-container failure the script cannot close: there is no earlier
# step to hide behind. The contract is that it says `may be OPEN` instead of
# pretending.
RESTORE_STUB_FAIL=1 runp on
rc_nonzero
err_has 'iptables rejected the minimal deny'
err_has 'may be OPEN'
jumps_are 0
jumps_are 0 ip6tables
# Two attempts, not one: the gate in the floor is the only rule there that needs a
# kernel module (`-m owner`), and a restore is one transaction — so a kernel
# without xt_owner would turn the fail-closed floor into an open one. The ungated
# floor is therefore tried before giving up, and the retry is said out loud.
log_is 'iptables-restore --noflush' 'iptables-restore --noflush'
err_has 'refused the resolver gate'
err_has 'the kernel may lack the owner match'
ok 'nothing beyond the floor was attempted, and the fallback floor is still a deny'
resolv_is_fixture

case_start 'a rotator that will not start fails the arm closed'
reset_world
SSD_STUB_FAIL=1 runp on
rc_nonzero
err_has 'the log rotator failed to start'
err_has 'grow unbounded'
# Same shape as a failed logger: the fence's exhaust growing without a bound is a
# failure state, not a degraded mode to arm into.
jumps_are 1
jumps_are 1 ip6tables
not_called 'dig'
resolv_is_fixture

case_start 'a floor that closes v4 but not v6 says which family is open'
reset_world
RESTORE_STUB_FAIL_MIN=ip6tables-restore runp on
rc_nonzero
err_has 'IPv6 may be OPEN'
err_has 'the IPv4 deny is in place'
jumps_are 1
jumps_are 0 ip6tables
resolv_is_fixture
# The die message and the report have to agree about what is enforced.
runp status
rc_is 0
out_has 'enforcement: partial — IPv4 armed, IPv6 off'
ok 'status names the split the arm died in the middle of'

case_start 'a failed re-arm never lifts the enforcement already in place'
reset_world
runp on
rc_is 0
jumps_are 1
: >"$STATE/calls.log"
DNSMASQ_STUB_START_FAIL=1 runp on
rc_nonzero
jumps_are 1
ok 'the jump was never removed to re-arm — enforcement held throughout'
not_called 'iptables -D OUTPUT'
file_has "$ROOT/etc/resolv.conf" 'nameserver 127.0.0.1'
ok 'the resolver configuration from the first arm stands'

# ============================================================================
# Toggling
# ============================================================================

case_start 'off removes only the jumps'
reset_world
runp on
rc_is 0
: >"$STATE/calls.log"
runp off
rc_is 0
out_has 'enforcement: off'
jumps_are 0
jumps_are 0 ip6tables
log_is \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'iptables -D OUTPUT -j DEV_FIREWALL' \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -D OUTPUT -j DEV_FIREWALL' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL'
ok 'the resolver and the logger are never signalled — off toggles enforcement only'
file_has "$ROOT/etc/resolv.conf" 'nameserver 127.0.0.1'
ok 'names keep resolving through dnsmasq while enforcement is off'
not_called 'ipset flush'

case_start 'off clears a stacked jump an interrupted arm could leave'
reset_world
runp on
rc_is 0
echo 3 >"$STATE/jumps-iptables"
: >"$STATE/calls.log"
runp off
rc_is 0
jumps_are 0
called_times 3 'iptables -D OUTPUT -j DEV_FIREWALL'
ok 'the delete loop drains every duplicate rather than one'

# ============================================================================
# Log retention
# ============================================================================

# The three logs at known sizes, the denial log alone big enough to cross the
# threshold the cases set — so "rotation is per-file" is observable rather than
# assumed. No arm needed: rotate is about files the daemons left behind.
plant_sized_logs() {
	printf 'x%.0s' {1..200} >"$LOG_DIR/dev-firewall.log"
	printf 'small dns\n' >"$LOG_DIR/dev-firewall-dns.log"
	printf 'small ulogd\n' >"$LOG_DIR/dev-firewall-ulogd.log"
	chmod 0644 "$LOG_DIR"/dev-firewall*.log
}

case_start 'rotate leaves every log below the threshold alone'
reset_world
plant_sized_logs
DEV_FIREWALL_LOG_MAX=1048576 runp rotate
rc_is 0
no_file "$LOG_DIR/dev-firewall.log.1"
no_file "$LOG_DIR/dev-firewall-dns.log.1"
no_file "$LOG_DIR/dev-firewall-ulogd.log.1"
file_size_is 200 "$LOG_DIR/dev-firewall.log"
ok 'a rotation that is not due writes nothing at all'

case_start 'a log past the threshold is rotated, one generation kept, per file'
reset_world
plant_sized_logs
DEV_FIREWALL_LOG_MAX=100 runp rotate
rc_is 0
file_size_is 200 "$LOG_DIR/dev-firewall.log.1"
file_size_is 0 "$LOG_DIR/dev-firewall.log"
ok 'copy-truncate: the generation holds the old bytes and the live file is emptied'
# Truncated in place rather than renamed, because both daemons hold the file open
# in append mode — and the mode has to survive, or the next reader cannot read it.
mode_is 644 "$LOG_DIR/dev-firewall.log"
mode_is 644 "$LOG_DIR/dev-firewall.log.1"
no_file "$LOG_DIR/dev-firewall-dns.log.1"
no_file "$LOG_DIR/dev-firewall-ulogd.log.1"
file_size_is 10 "$LOG_DIR/dev-firewall-dns.log"
file_size_is 12 "$LOG_DIR/dev-firewall-ulogd.log"
ok 'the two logs below the threshold are untouched — the bound is per file'

case_start 'rotate --force rotates all three regardless of size'
reset_world
plant_sized_logs
runp rotate --force
rc_is 0
file_size_is 200 "$LOG_DIR/dev-firewall.log.1"
file_size_is 10 "$LOG_DIR/dev-firewall-dns.log.1"
# ulogd's own log too: three files grow, so three are bounded.
file_size_is 12 "$LOG_DIR/dev-firewall-ulogd.log.1"
file_size_is 0 "$LOG_DIR/dev-firewall.log"
file_size_is 0 "$LOG_DIR/dev-firewall-dns.log"
file_size_is 0 "$LOG_DIR/dev-firewall-ulogd.log"

case_start 'a second rotation replaces the generation instead of stacking them'
printf 'fresh\n' >"$LOG_DIR/dev-firewall.log"
runp rotate --force
rc_is 0
file_size_is 6 "$LOG_DIR/dev-firewall.log.1"
no_file "$LOG_DIR/dev-firewall.log.2"
no_file "$LOG_DIR/dev-firewall.log.1.1"
ok 'one generation is the whole retention — a second would double the bound'

case_start 'rotate on a container that was never armed exits clean'
reset_world
runp rotate
rc_is 0
log_empty
no_file "$LOG_DIR/dev-firewall.log"
no_file "$LOG_DIR/dev-firewall.log.1"
ok 'an absent log is a no-op, not a failure — the timer runs before the first arm too'

case_start 'a log that cannot be truncated fails the rotation and names the file'
reset_world
plant_sized_logs
if [ "$(id -u)" = 0 ]; then
	ok 'skipped: the suite is running as root, where the mode does not bite'
else
	chmod 0444 "$LOG_DIR/dev-firewall-dns.log"
	runp rotate --force
	# The one outcome that leaves a log unbounded, so it is the one that must not
	# be reported as a rotation: the timer's loop exits on it and status then says
	# `rotator: down` instead of supervising nothing.
	rc_nonzero
	err_has "cannot truncate $LOG_DIR/dev-firewall-dns.log"
	# All three are still attempted — freeing the filesystem is the point.
	file_size_is 0 "$LOG_DIR/dev-firewall.log"
	file_size_is 0 "$LOG_DIR/dev-firewall-ulogd.log"
	chmod 0644 "$LOG_DIR/dev-firewall-dns.log"
fi

# ============================================================================
# status
# ============================================================================

# plant_logs — a denial log with four destinations (one of them twice) and a
# dnsmasq query log that knows one of them, so every annotation path appears in
# one report. The line without DPT=/PROTO= is the one no real fixture would
# produce on demand and the tab-separated hand-off would mis-column.
plant_logs() {
	cat >"$ROOT/var/log/dev-firewall.log" <<-'LOG'
		Aug 11 09:14:02 host dev-firewall IN= OUT=eth0 MAC= SRC=10.9.0.7 DST=198.51.100.4 LEN=60 PROTO=TCP SPT=44100 DPT=443 SYN URGP=0
		Aug 11 09:14:03 host dev-firewall IN= OUT=eth0 MAC= SRC=10.9.0.7 DST=203.0.113.9 LEN=60 PROTO=TCP SPT=44102 DPT=22 SYN URGP=0
		Aug 11 09:14:04 host dev-firewall IN= OUT=eth0 MAC= SRC=10.9.0.7 DST=192.0.2.77 LEN=60 PROTO=UDP SPT=51000 DPT=53 URGP=0
		Aug 11 09:14:05 host dev-firewall IN= OUT=eth0 MAC= SRC=10.9.0.7 DST=192.0.2.99 LEN=60 URGP=0
		Aug 11 09:14:06 host dev-firewall IN= OUT=eth0 MAC= SRC=10.9.0.7 DST=198.51.100.4 LEN=60 PROTO=TCP SPT=44108 DPT=443 SYN URGP=0
	LOG
	cat >"$ROOT/var/log/dev-firewall-dns.log" <<-'LOG'
		Aug 11 09:14:01 dnsmasq[4242]: query[A] telemetry.example.org from 127.0.0.1
		Aug 11 09:14:01 dnsmasq[4242]: reply telemetry.example.org is 198.51.100.4
		Aug 11 09:14:01 dnsmasq[4242]: reply stale.example.org is 198.51.100.4
		Aug 11 09:14:01 dnsmasq[4242]: reply telemetry.example.org is 198.51.100.4
	LOG
}

case_start 'status annotates each denial with the domain it was aimed at'
reset_world
runp on
rc_is 0
plant_logs
: >"$STATE/calls.log"
# awk on the case PATH from here on: the single-pass claim below is about how many
# times the DNS log is read, which is only observable in the call log.
# shellcheck disable=SC2086
grant $ALL_STUBS awk
runp status
rc_is 0
out_has 'enforcement: armed'
out_matches "^resolver: up \(pid $DNSMASQ_PID_VALUE\)$"
out_matches "^logger: up \(pid $ULOGD_PID_VALUE\)$"
out_matches "^rotator: up \(pid $ROTATE_PID_VALUE\)$"
ok 'the third daemon the fence supervises is in the report too'
# The allowlist as the file says it, comments and blanks dropped — what the
# agent sees and cannot change.
out_has 'allowlist: anthropic.com claude.ai openai.com github.com npmjs.org herdr.dev playwright.download.prss.microsoft.com'
out_hasnt 'fixture allowlist'
out_hasnt 'source hosting'
out_has 'recent denials:'
# Resolver correlation: dnsmasq's own query log knows which name produced it.
out_matches '^  Aug 11 09:14:02  198\.51\.100\.4:443/TCP  telemetry\.example\.org$'
ok 'the latest answer wins when a domain and a stale one share an address'
# Reverse lookup is the fallback, and it goes back through NSS.
out_matches '^  Aug 11 09:14:03  203\.0\.113\.9:22/TCP  reverse\.example\.net$'
called 'getent hosts 203.0.113.9'
# Neither source knows this one, and an unknown domain is said so rather than
# guessed.
out_matches '^  Aug 11 09:14:04  192\.0\.2\.77:53/UDP  \?$'
ok 'ports and protocols come from the log line, not from assumptions'
# A line whose port and protocol are missing renders as placeholders in their own
# columns: the annotation is handed to the shell tab-separated, and tab is IFS
# *whitespace*, so a genuinely empty field would collapse and shift the protocol
# into the port column.
out_matches '^  Aug 11 09:14:05  192\.0\.2\.99:\?/\?  \?$'
out_matches '^  Aug 11 09:14:06  198\.51\.100\.4:443/TCP  telemetry\.example\.org$'
ok 'a second denial to a known address is annotated from the same single pass'
# The single-pass claim itself: five denials, one read of the DNS log.
called_times 1 "$ROOT/var/log/dev-firewall-dns.log"
ok "status's cost does not grow with the size of the DNS log"

case_start 'status reports a wedged fence honestly'
# Enforcement armed with the resolver dead is exactly what a failed arm leaves
# behind, and the report has to be able to say so.
rm -rf "$ROOT/proc/$DNSMASQ_PID_VALUE"
runp status
rc_is 0
out_has 'enforcement: armed'
out_has 'resolver: down'
out_matches "^logger: up \(pid $ULOGD_PID_VALUE\)$"
ok 'armed alongside a dead resolver is reportable, not a contradiction'

case_start 'status names a half-armed fence instead of rounding it to armed'
# Both families are checked because an arm can die between them, and `armed`
# with IPv6 wide open would be the report the operator debugs against.
reset_world
runp on
rc_is 0
echo 0 >"$STATE/jumps-ip6tables"
runp status
rc_is 0
out_has 'enforcement: partial — IPv4 armed, IPv6 off'
out_hasnt 'enforcement: armed'
called 'ip6tables -C OUTPUT -j DEV_FIREWALL'
echo 0 >"$STATE/jumps-iptables"
echo 1 >"$STATE/jumps-ip6tables"
runp status
rc_is 0
out_has 'enforcement: partial — IPv4 off, IPv6 armed'
out_hasnt 'enforcement: off'
ok 'neither family alone is allowed to speak for enforcement'

case_start 'status on a container that was never armed says so and writes nothing'
reset_world
runp status
rc_is 0
out_has 'enforcement: off'
out_has 'resolver: down'
out_has 'logger: down'
out_has 'rotator: down'
out_has 'allowlist: anthropic.com'
out_has 'no denials logged'
# Not a word on stderr either: the logs do not exist yet, and a report that
# complained about them would be the noise every container start begins with.
err_empty
log_is \
	'iptables -C OUTPUT -j DEV_FIREWALL' \
	'ip6tables -C OUTPUT -j DEV_FIREWALL'
ok 'no daemon is started and no rule is touched by a report'
no_file "$CONF/dnsmasq.conf"
no_file "$RUN"
resolv_is_fixture

case_start 'status reports a missing or empty allowlist instead of dying over it'
reset_world
rm -f "$ALLOWLIST"
runp status
rc_is 0
out_has "allowlist: (missing: $ALLOWLIST)"
err_empty
printf '# only comments\n' >"$ALLOWLIST"
runp status
rc_is 0
out_has 'allowlist: (empty)'
ok 'a report is a report — the arm is where a bad allowlist fails'

# ============================================================================
# Escalation
# ============================================================================

case_start 'a non-root run escalates through the argument-scoped grant'
reset_world
ID_STUB_UID=1000 runp status
rc_is 0
# Asked of the exact vector, and of the image path: sudoers lists the subcommands
# it grants, and the planted copy's own location is never what gets escalated.
log_is \
	"sudo -n -l $SELF status" \
	"sudo -n $SELF status"
ok 'nothing is attempted unprivileged first'
not_called "$REPO"
ok 'the path escalated is the image copy, not the file that ran'

case_start 'a subcommand flag survives the escalation'
reset_world
# Every granted subcommand escalates, and the smoke check runs `rotate --force`
# as the `dev` identity: a flag the re-exec dropped would be unreachable.
ID_STUB_UID=1000 runp rotate --force
rc_is 0
log_is \
	"sudo -n -l $SELF rotate --force" \
	"sudo -n $SELF rotate --force"

case_start 'on escalates too — it is how the container arms itself at start'
reset_world
ID_STUB_UID=1000 runp on
rc_is 0
log_is \
	"sudo -n -l $SELF on" \
	"sudo -n $SELF on"

case_start 'off is refused to a non-root caller without asking sudo'
reset_world
runp on
rc_is 0
: >"$STATE/calls.log"
ID_STUB_UID=1000 runp off
rc_nonzero
err_has 'off is not granted inside the container'
err_has 'devc firewall off'
# Not even the grant probe: the refusal is this script's own policy, not sudo's
# answer, so an operator reading the message learns where `off` lives.
log_empty
jumps_are 1
jumps_are 1 ip6tables
ok 'enforcement stands — the agent identity cannot lift the fence'

case_start 'a missing sudoers grant names the fix instead of the symptom'
reset_world
SUDO_STUB_LIST_RC=1 ID_STUB_UID=1000 runp on
rc_nonzero
err_has 'could not escalate'
err_has '/etc/sudoers.d/dev-firewall'
err_has 'granting `dev-firewall on`'
err_has 'devc rebuild'
log_is "sudo -n -l $SELF on"
ok 'the grant is probed before the run, so a failing subcommand is not misreported'

# ============================================================================
# The host guard
# ============================================================================

case_start 'without the container sentinel it refuses to run'
reset_world
# An absent path rather than an unset variable: on a Linux host that is itself
# inside a container, /.dockerenv exists and the default would pass.
SENTINEL="$TMP/no-such-sentinel"
runp on
rc_nonzero
err_has 'not inside a container'
err_has 'must never run on the host'
log_empty
resolv_is_fixture
no_file "$CONF/dnsmasq.conf"
ok 'nothing on the host was touched'

case_start 'the guard covers the read-only subcommand too'
reset_world
SENTINEL="$TMP/no-such-sentinel"
runp status
rc_nonzero
err_has 'not inside a container'
log_empty

# ============================================================================
# Usage
# ============================================================================

case_start 'an unknown argument prints usage on stderr'
reset_world
runp --wat
rc_is 2
err_has 'unknown argument: --wat'
err_has 'Usage: dev-firewall'
log_empty
no_file "$CONF/dnsmasq.conf"

case_start 'no subcommand is a usage error, not a default action'
reset_world
runp
rc_is 2
err_has 'Usage: dev-firewall'
log_empty
no_file "$CONF/dnsmasq.conf"
ok 'a bare invocation never arms or disarms anything'

case_start '--force belongs to rotate alone'
reset_world
runp status --force
rc_is 2
err_has '--force applies to rotate only'
err_has 'Usage: dev-firewall'
log_empty
ok 'a flag on the wrong subcommand is a usage error, not a silently ignored word'
runp --force
rc_is 2
err_has 'Usage: dev-firewall'
log_empty

case_start 'two subcommands at once are refused'
reset_world
runp on off
rc_is 2
err_has 'one subcommand at a time'
log_empty

case_start '--help prints usage on stdout and runs nothing'
reset_world
runp --help
rc_is 0
out_has 'Usage: dev-firewall'
out_has 'Arm the fence'
out_has 'devc firewall allow'
log_empty
no_file "$CONF/dnsmasq.conf"
ok 'help works outside the container too — it is the one thing that must'

finish
