# The devcontainer's shell defaults, baked into the image at
# /etc/zsh/devcontainer.zshrc and sourced from Debian's /etc/zsh/zshrc, so the
# packaged terminfo key bindings stay and ~/.zshrc runs after this and wins.
# System rc, not a home dotfile: the home volume shadows image content under
# /home/dev. See README.md ("Shell, editor and clipboard").

# PATH. The login shell's /etc/profile resets PATH for non-root users and drops
# /usr/local/sbin, where the fence and the volume repair live, and never knew
# about the home's bin, where the bootstrap installs claude, codex and herdr.
# typeset -U keeps each entry once however many shells nest.
typeset -U path
path=(~/.local/bin /usr/local/sbin $path)

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
# SHARE_HISTORY writes each command as it runs and imports other panes'; zsh
# documents INC_APPEND_HISTORY as the one to leave off when it is on.
setopt SHARE_HISTORY

autoload -Uz compinit && compinit

# fzf's own zsh integration: fuzzy history on Ctrl-R, files on Ctrl-T,
# directories on Alt-C, and `**<Tab>` completion. Generated by the binary
# rather than sourced from a file so it always matches the installed version.
# Unguarded on purpose, like the plugin sources below: a missing fzf should
# break every shell loudly rather than silently hand Ctrl-R back to zsh's
# incremental search. Sources before the key bindings below, which are meant
# to win, and before the highlighting, which wraps the widgets that exist when
# it loads.
source <(fzf --zsh)

# History walk on Ctrl-K/Ctrl-J and the arrows: the prefix-aware variant, so
# with `git ` typed the keys step through git commands only. Debian's packaged
# zshrc binds the arrows to the plain up/down-line-or-history through
# terminfo; these bind the same terminfo entries, so they win on any terminal
# the packaged rc covers, and the two literal escape forms catch a terminal
# whose keypad mode differs from what terminfo claims, as inside herdr's panes.
# Ctrl-K replaces kill-line and Ctrl-J replaces accept-line, knowingly.
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^K' up-line-or-beginning-search
bindkey '^J' down-line-or-beginning-search
for key in "${terminfo[kcuu1]}" '^[[A' '^[OA'; do
	[ -n "$key" ] && bindkey "$key" up-line-or-beginning-search
done
for key in "${terminfo[kcud1]}" '^[[B' '^[OB'; do
	[ -n "$key" ] && bindkey "$key" down-line-or-beginning-search
done
unset key

alias g=git
compdef g=git

# Unguarded on purpose: a Debian rename should fail loudly in every shell
# rather than silently drop the feature. Highlighting sources last, as it
# documents.
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Prompt: user@host:cwd[branch]. The branch comes from zsh's own vcs_info, not
# a prompt framework or a `git branch` call in the prompt string — vcs_info is
# shipped with zsh, and as a precmd hook it queries git once per prompt rather
# than on every redraw. PROMPT_SUBST is what makes the ${...} re-expand each
# time; without it the branch would freeze at whatever it was when the shell
# started. Outside a repository vcs_info leaves the variable empty, so the
# brackets disappear rather than showing up blank.
autoload -Uz vcs_info add-zsh-hook
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '[%b]'
zstyle ':vcs_info:git:*' actionformats '[%b|%a]'
add-zsh-hook precmd vcs_info
setopt PROMPT_SUBST
PROMPT='%n@%m:%~${vcs_info_msg_0_}%# '

# yazi's documented cd-on-quit wrapper, verbatim from its quick-start docs: it
# passes yazi a --cwd-file to write the directory it exited in, then cds there.
# Copied rather than adapted so it stays diffable against upstream.
function y() {
	local tmp cwd; tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd" || builtin true
	command rm -f -- "$tmp"
}
